### ISSUE TITLE
Bug / Error

### ISSUE THREAD

**Issue by ghost** [Huguitis/globalchatbot#11]
![image](https://i.imgur.com/bbWImpk.png)

Each word i send in the global chat channel, it automaticallys detected like a harassment and i dont know why .-. @Huguitis

**Comment by ghost** [comment]
![image2](https://i.imgur.com/6PxqCPT.png)

**Comment by Huguitis** [comment]
Hello, please send you settings.js file without your bot's token.

**Comment by ghost** [comment]
module.exports = {
    BotToken: "",
    OwnerID: "734380380232220785",
    ImgBBApiKey: "I dont want to show it",
    SupportServerInvite: "https://discord.gg/6aGjSgxMYe",
    BlockedContent: "The real settings.js have the words that must be blocked ",

    SuccessEmoji: "<a:success:1063119760147103806>",
    ErrorEmoji: "<a:error:1063119608149717042>",
    LoadingEmoji: "<a:loading:1063119460434706493>",
    NotifyEmoji: "<:notify:1063120126389522452>",
    RoleUserEmoji: "<:user:1063119250954403952>",
    RoleModeratorEmoji: "<:moderator:1063118964546351214>",
    RoleOwnerEmoji: "<:owner:1063118529873842378>"
  }

**Comment by TheGamer3514** [comment]
send the blocked words as it appears to be an issue with them.

**Comment by ghost** [comment]
the blocked words that i have are the same as the settings.json of this repository :)

**Comment by TheGamer3514** [comment]
can you send anything? not even "hi"?

**Comment by ghost** [comment]
i tryed to send random things like ''lol'' ''hey guys how are you'' and more randoms stuff and copy pasting from lorem ipsum and same .-.

**Comment by TheGamer3514** [comment]
have you modified anything other than settings file?

**Comment by ghost** [comment]
Ye, i have modified the Huguitis Nodes Hosting at ping.js file
